Add optional ctl_connection_settings, force failure when can't get Table Metadata
cccc1999/python-mysql-replication pull request #1
Opened 2016-03-22 23:39 UTC by kdparker

Failure on replication handler when it can't get table metadata looks like this:
https://pb.yelpcorp.com/188948

This branch was tested using branch keegan_DATAPIPE-844-replhandler in the replication handler (where running it with this fix caused DATAPIPE-786 to be fixed without using the bandaid refresh runner)

2016-03-23 00:36 UTC, jcnnghm commented on pymysqlreplication/binlogstream.py
> +        self._ctl_connection_settings = ctl_connection_settings
Do you need to set a charset for this too?

2016-03-23 00:54 UTC, jcnnghm commented on pymysqlreplication/row_event.py
> +            raise TableMetadataUnavailableError("Table Metadata could not be read for {}".format(self.table))
Maybe this should be optional?  I absolutely want it, but the maintainer didn't - I think it's much more correct to raise an exception, but if we want to contribute back upstream, we probably shouldn't force the issue.

2016-10-17 22:06 UTC, premsantosh requested changes

2016-10-17 22:06 UTC, premsantosh commented on pymysqlreplication/binlogstream.py
> +                 fail_on_table_metadata_unavailable=False):
Is this a temporary flag? And why is it defaulted to false? When do we not want to get alerted?

2016-10-17 22:06 UTC, premsantosh commented on pymysqlreplication/exceptions.py
> +    pass
Would be nice to have a little context with this. Maybe something like:
```
class TableMetadataUnavailableError(Exception):
  def __init__(self, table_name, cluster):
    Exception.__init__(self, "Unable to find metadata for table {t} in cluster {c}".format(..))
```

2016-10-17 22:10 UTC, kdparker commented on pymysqlreplication/binlogstream.py
> +                 fail_on_table_metadata_unavailable=False):
I think the intention was we eventually wanted to merge this in to the overall master branch of the library, and to do so we want to keep existing functionality exactly the same (the corresponding branch in replhandler sets this to True).

Do we want to make this default to True?

2016-10-17 22:12 UTC, kdparker commented
Something else we may want to consider is migrating this to another user/merge it in to the noplay master (can anyone here actually merge these changes?)

2016-10-17 22:14 UTC, premsantosh commented on pymysqlreplication/binlogstream.py
> +                 fail_on_table_metadata_unavailable=False):
Aah I see, that makes sense. If we are setting it to true from our side then it should be fine.

2016-11-28 18:33 UTC, kdparker commented
Not using this branch anymore, closing

2016-11-28 18:33 UTC, closed without merging